Repository QGEP/datamodel, pull requests merged in 2023-03, with the labels that each got.

#146 fix for https://github.com/QGEP/QGEP/issues/591 : run drop_views.sql …
  07_network_tracking.sql
  13_import.sql
  delta/delta_1.0.1_prefix_reach_view.sql
  delta/delta_1.0.1_prefix_wastewater_structure_view.sql
  delta/delta_1.0.1_view_for_files.post.sql
  delta/delta_1.1.0_quarantine.post.sql
  delta/delta_1.1.0_vw_ogranisation_geom_cast.sql
  delta/delta_1.1.0_vw_qgep_wastewater_structure_fixes.sql
  delta/delta_1.1.1_default_value_vw_wastewater_node.sql
  delta/delta_1.1.1_quarantine_calculations.sql
  delta/delta_1.2.0_geometry_altitude.post.sql
  delta/delta_1.2.0_quarantine_type_update.sql
  delta/delta_1.2.0_reach_on_delete_rule.sql
  delta/delta_1.2.1_fix_vw_qgep_wastewater_structure.sql
  delta/delta_1.3.0_import_trigger.sql
  delta/delta_1.4.0_import_views.sql
  delta/delta_1.4.0_swmm_views.sql
  delta/delta_1.4.1_swmm_catchment_areas.sql
  delta/delta_1.5.5_add_spatial_index_on_network_views.sql
  delta/pre-all.py
  scripts/db_setup.sh
  view/create_views.py
  view/drop_views.sql
  view/network/vw_network_node.sql
  view/network/vw_network_segment.sql
  view/vw_qgep_import.sql
Labels: Sprint, durability

#190 Qgep swmm phase3 enhancements
  03_qgep_db_dss.sql
  05_data_model_extensions.sql
  09_qgep_dictionaries.sql
  delta/delta_1.5.8_add_reach_default_coefficient_friction.sql
  delta/delta_1.5.8_add_reach_hydraulic_load.sql
  delta/delta_1.5.8_tbl_swmm_coefficient_friction.sql
  swmm_views/01_vw_swmm_create_schema.sql
  swmm_views/02_vw_swmm_junctions.sql
  swmm_views/03_vw_swmm_aquifers.sql
  swmm_views/04_vw_swmm_conduits.sql
  swmm_views/05_vw_swmm_dividers.sql
  swmm_views/06_vw_swmm_landuses.sql
  swmm_views/07_vw_swmm_losses.sql
  swmm_views/08_vw_swmm_outfalls.sql
  swmm_views/09_vw_swmm_subcatchments.sql
  swmm_views/10_vw_swmm_subareas.sql
  swmm_views/11_vw_swmm_dwf.sql
  swmm_views/11_vw_swmm_pumps.sql
  swmm_views/12_vw_swmm_raingages.sql
  swmm_views/13_vw_swmm_infiltrations.sql
  swmm_views/14_vw_swmm_coverages.sql
  swmm_views/14_vw_swmm_xsections.sql
  swmm_views/15_vw_swmm_coordinates.sql
  swmm_views/15_vw_swmm_vertices.sql
  swmm_views/16_vw_swmm_pumps.sql
  swmm_views/17_vw_swmm_polygons.sql
  swmm_views/18_vw_swmm_storages.sql
  swmm_views/19_vw_swmm_outlets.sql
  swmm_views/20_vw_swmm_orifices.sql
  swmm_views/21_vw_swmm_weirs.sql
  swmm_views/22_vw_swmm_curves.sql
  swmm_views/23_vw_swmm_xsections.sql
  swmm_views/24_vw_swmm_coordinates.sql
  swmm_views/25_vw_swmm_tags.sql
  swmm_views/26_vw_swmm_symbols.sql
  swmm_views/27_vw_swmm_results.sql
  system/CURRENT_VERSION.txt
  test/test_swmm.py
  view/create_views.py
Labels: feature

#187 Adjust vw qgep overflow
  06_symbology_functions.sql
  view/vw_oo_overflow.yaml
Labels: bug

#207 Provide rights for qgep_swmm and qgep_import schemas
  12_1_roles.sql
Labels: bug

#186 Labeling of wastewater structures with multiple wastewater nodes
  06_symbology_functions.sql
  delta/delta_1.5.9_adjust_ws_labeling.sql
  system/CURRENT_VERSION.txt
  test/test_triggers.py
Labels: feature

#209 Modify drop views order
  view/drop_views.sql
Labels: bug
